<?php    $title = 'Sign up';?>
<?php require 'templates/layout/header.phtml'; ?>
<form id="formLogin" action="SingupUser" method="post">
    <input type="text" name="usuario" id="input-usuario" placeholder="Usuario..." required>
    <input type="password" name="password" id="input-password" placeholder="Contraseña..." required>
    <input type="password" name="password-confirm" id="input-confirm-password" placeholder="Confirmar contraseña..." required>
    <input type="submit" value="Enviar" id="btnSubmit">
</form>
<?php require 'templates/layout/footer.phtml'; ?>