<?php    $title = 'Log In';?>
<?php require 'templates/layout/header.phtml'; ?><form id="formLogin" action="auth" method="post">
    <input type="text" name="username" id="input-username" placeholder="Usuario..." required>
    <input type="password" name="password" id="input-password" placeholder="Contraseña..." required>
    <input type="submit" value="Enviar" id="btnSubmit">
</form>
<?php require 'templates/layout/footer.phtml'; ?>