<?php    $title = htmlspecialchars($pelicula->titulo);?>
<?php require 'templates/layout/header.phtml'; ?>

<div class="item">
    <div class="item-image">
        <img src="<?= BASE_URL ?>frontend/images/poster.jpg" alt="">
    </div>
    <div class="item-info">
        <h1> <?= htmlspecialchars($pelicula->titulo) ?> </h1>
        <h2> <?= htmlspecialchars($pelicula->director) ?> </h2>
        <h3> <?= htmlspecialchars($pelicula->anio) ?> </h3>
        <p> <?= htmlspecialchars($pelicula->descripcion) ?> </p>
    </div>
</div>
<script src="<?= BASE_URL ?>frontend/js/item.js"></script>
<?php require 'templates/layout/footer.phtml'; ?>