<?php    $title = $genero->nombre;?>
<?php require 'templates/layout/header.phtml'; ?>

<div class="genero-container">
    <?php if ($this->res->user && $this->res->user->role == 'admin'): ?>
        <button id="edit-button" ">Editar</button>
        <a href="<?=htmlspecialchars(BASE_URL)?>eliminarGenero/<?= htmlspecialchars($genero->id)?>"><button id="delete-button">Borrar</button></a>
    <?php endif; ?>
    <h1> <?= htmlspecialchars($genero->nombre)?> </h1>
    <h3>Edad objetiva: <?= htmlspecialchars($genero->clasificacion_por_edad)?></h3>
    <h2>Descripcion:</h2>
    <p><?= htmlspecialchars($genero->descripcion)?></p>
    <a href = "<?= htmlentities(BASE_URL) ?>peliculas/<?= htmlspecialchars($genero->nombre)?>"><p>Ver peliculas de <?= htmlspecialchars($genero->nombre)?></p></a>
</div>

<?php if ($this->res->user && $this->res->user->role == 'admin'): ?>
    <form action="<?= BASE_URL ?>editarGenero" method="post" id="formGenero" class="hidden">
        <input type="text" name="nombre" id="nombre" placeholder="Nombre del genero..." value="<?= htmlspecialchars($genero->nombre)?>" required>
        <input type="text" name="clasificacion_por_edad" id="clasificacion_por_edad" placeholder="Clasificacion por edad..." value="<?= htmlspecialchars($genero->clasificacion_por_edad)?>" required>
        <textarea name="descripcion" id="descripcion" placeholder="Descripcion..."><?= htmlspecialchars($genero->descripcion)?></textarea>
        <input type="submit" value="Enviar" id="btnSubmit">
    </form>
<?php endif; ?> 
<script src="<?= BASE_URL ?>frontend/js/itemGenero.js"></script>
<?php require 'templates/layout/footer.phtml'; ?>