<?php $title = $title ?? '';?>
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="<?= BASE_URL ?>frontend/css/style.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php if ($title): ?>
        <title><?= htmlspecialchars($title) ?></title>
    <?php else: ?>
        <title>Titulo</title>
    <?php endif; ?>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="<?= htmlspecialchars(BASE_URL) ?>">Home</a></li>
                <li><a href="<?= htmlspecialchars(BASE_URL) ?>peliculas">Peliculas</a></li>
                <li><a href="<?= htmlspecialchars(BASE_URL) ?>generos">Categorías</a></li>
                <?php if ($this->res->user && $this->res->user->role == 'admin'): ?> 
                    <li class="btn-agregar-pelicula"><a href="<?= htmlspecialchars(BASE_URL) ?>nuevaPelicula">Agregar pelicula</a></li>
                <?php endif; ?>
            </ul>
            <?php if ($this->res->user): ?>
                <div class="btnLogin"><a href="<?= BASE_URL ?>logout">Log Out</a></div>
            <?php else: ?>
                <div class="btnLogin"><a href="<?= BASE_URL ?>login">Log In</a></div>
            <?php endif; ?>
        </nav>
    </header>