<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
    <link rel="stylesheet" href="<?= BASE_URL ?>frontend/css/style.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="<?= BASE_URL ?>">Home</a></li>
                <li><a href="<?= BASE_URL ?>peliculas">Peliculas</a></li>
                <li><a href="<?= BASE_URL ?>generos">Categorias</a></li>
            </ul>
            <div class="btnLogin"><a href="<?= BASE_URL ?>login">Log In</a></div>
        </nav>
    </header>